[project]
dependencies = [
  "dj-database-url>=3.0.1",
  "django>=5.2.4",
  "psycopg>=3.2.9",
  "python-dotenv>=1.1.1",
]
name = "plant-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
