# Generated by Django 5.2.4 on 2025-08-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MoistureLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('moisture_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moisture_logs',
                'ordering': ['-datetime'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plant_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantDeviceRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('unregistered_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='plants.devices')),
                ('plant', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, to='plants.plants')),
            ],
            options={
                'db_table': 'plant_device_registration',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='plants',
            name='scientific_name',
            field=models.ForeignKey(blank=True, db_column='scientific_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.planttypes'),
        ),
    ]
