# Generated by Django 5.2.4 on 2025-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moisturelogs',
            options={'managed': False, 'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='plantdeviceregistration',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='plants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='planttypes',
            options={'managed': False},
        ),
    ]
