# Generated by Django 5.2.4 on 2025-09-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_devices_options_alter_moisturelogs_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('watering', 'watering'), ('repot', 'repot'), ('environment change', 'environment change'), ('cuttings', 'cuttings')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('dead', 'dead'), ('worsening', 'worsening'), ('bad', 'bad'), ('improving', 'improving'), ('healthy', 'healthy'), ('thriving', 'thriving')], default='healthy', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plants',
                'db_table': 'health_checkin',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='plantdeviceregistration',
            name='device',
        ),
        migrations.DeleteModel(
            name='MoistureLogs',
        ),
        migrations.RemoveField(
            model_name='plantdeviceregistration',
            name='plant',
        ),
        migrations.AlterModelOptions(
            name='planttypes',
            options={'managed': False, 'verbose_name_plural': 'Plant Types'},
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.DeleteModel(
            name='PlantDeviceRegistration',
        ),
    ]
